name: Notify Backend of New APK Release

on:
  release:
    types: [published]

jobs:
  notify-django:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Data to Django Webhook
        run: |
          curl -X POST https://<YOUR-PRODUCTION-DJANGO-DOMAIN>/api/app-config/webhook/github/ \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.APPCONFIG_SECRET }}" \
          -d '${{ toJson(github.event) }}'
